### ISSUE TITLE
ObjectMapper(s) are allocated per each report generation

### ISSUE THREAD

**Issue by franz1981** [RedHatInsights/insights-java-client#118]
Jackson ObjectMapper(s) could be cached (as instance fields, in case we need some specific configuration) instead of being recreated and re-configured before producing reports.
In case there is some context-specific configuration eg

```java
    ObjectMapper mapper = new ObjectMapper();

    SimpleModule simpleModule =
        new SimpleModule(
            "SimpleModule", new Version(1, 0, 0, null, "com.redhat.insights", "runtimes-java"));
    // getClass can change depending who subclass `this`!!!!!!! <------------------------------------------------- THIS ONE! 
    simpleModule.addSerializer(getClass(), getSerializer());
    mapper.registerModule(simpleModule);
    // .. other code 
 ```   
In such cases we can both provide a lazy allocation for it (not important if racy or not, `ObjectMapper` is thread-safe, just need to safe publishing it) and storing it in the relevant instance field.

**Comment by jponge** [comment]
Done in #117
