### ISSUE TITLE
Consume the upstream artefacts from an unauthenticated Maven repository

### ISSUE THREAD

**Issue by fax4ever** [RedHatInsights/insights-java-client#119]
Hi everyone,

According to [the readme](https://github.com/RedHatInsights/insights-java-client#consuming-this-library) seems to be possible to consume the upstream artifacts using the GitHub project's Apache Maven repository.
Trying to do that, I came across [this issue](https://github.com/orgs/community/discussions/26634).
Is there any way to workaround it?
Thanks

**Comment by jponge** [comment]
Currently going through https://central.sonatype.org/publish/publish-guide/#releasing-to-central to register the project

**Comment by fax4ever** [comment]
Thank you @jponge

**Comment by jponge** [comment]
Update: https://issues.sonatype.org/browse/OSSRH-93496 has been handled, I'm now updating the release workflow, and also fighting some Maven Central requirements rules, especially making sure that the `jboss-cert-helper` have dummy `sources` and `javadoc` and `jar` artifacts.

**Comment by jponge** [comment]
We will not publish the `jboss-cert-helper` to Maven Central.

**Comment by fax4ever** [comment]
Thank you @jponge for the effort
