### ISSUE TITLE
Missing reference to a distribution repository

### ISSUE THREAD

**Issue by tdiesler** [RedHatInsights/insights-java-client#71]
Please add a reference to the distribution repository, or document how a dependency to this library can be created.

**Comment by jponge** [comment]
Hi @tdiesler, this is a product-only library, we don't publish it to any upstream repository.

Other than that it's a classic Maven project, the resulting artefacts can be published to any local or remote repository (see `mvn install` for local deployment, `mvn deploy` for remote deployment).

**Comment by tdiesler** [comment]
... and why aren't you publishing to a redhat internal repo?

If I publish to such a repo, chances are that some other project will pick a different (redhat) repo that they publish this dependency to. I'd rather have you pick the repo that releases of this library are published to.

**Comment by jponge** [comment]
Productised bits are being published internally.
